version: '3.8'

services:
  angular-app:
    build: ./skyrise-furniture
    ports:
      - "4200:80"
    container_name: skyrise-angular
    restart: unless-stopped
    command: >
      sh -c "echo '🚀 Angular app starting at http://localhost:4200' && 
             nginx -g 'daemon off;'"
    
  nextjs-app:
    build: ./skyrise-furniture-nextjs
    ports:
      - "3000:3000"
    container_name: skyrise-nextjs
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    command: >
      sh -c "echo '🚀 Next.js app starting at http://localhost:3000' && 
             node server.js"