version: '3.8'

services:
  angular-app:
    build: ./skyrise-furniture
    ports:
      - "4200:80"
    container_name: skyrise-angular
    restart: unless-stopped
    
  nextjs-app:
    build: ./skyrise-furniture-nextjs
    ports:
      - "3000:3000"
    container_name: skyrise-nextjs
    environment:
      - NODE_ENV=production
    restart: unless-stopped