version: '3.8'

services:
  skyrise-furniture:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skyrise-furniture-app
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s